package com.tzq.dal.model;

import java.io.Serializable;
import java.util.Date;

public class TestOrder extends TestOrderKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.area_type
     *
     * @mbg.generated
     */
    private String areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.source_id
     *
     * @mbg.generated
     */
    private String sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.airline_code
     *
     * @mbg.generated
     */
    private String airlineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.UpdateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.order_type
     *
     * @return the value of test_order.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.order_type
     *
     * @param orderType the value for test_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.order_status
     *
     * @return the value of test_order.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.order_status
     *
     * @param orderStatus the value for test_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.area_type
     *
     * @return the value of test_order.area_type
     *
     * @mbg.generated
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.area_type
     *
     * @param areaType the value for test_order.area_type
     *
     * @mbg.generated
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.source_id
     *
     * @return the value of test_order.source_id
     *
     * @mbg.generated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.source_id
     *
     * @param sourceId the value for test_order.source_id
     *
     * @mbg.generated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.airline_code
     *
     * @return the value of test_order.airline_code
     *
     * @mbg.generated
     */
    public String getAirlineCode() {
        return airlineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.airline_code
     *
     * @param airlineCode the value for test_order.airline_code
     *
     * @mbg.generated
     */
    public void setAirlineCode(String airlineCode) {
        this.airlineCode = airlineCode == null ? null : airlineCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.UpdateTime
     *
     * @return the value of test_order.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.UpdateTime
     *
     * @param updatetime the value for test_order.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}