server:
    port: 9999
    address: 0.0.0.0
    sessionTimeout: 30
    contextPath: /

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



logdb:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.139.13:3306/gj_monitorlog
    username: root
    password: 1989513bs
    mappinglocation: classpath*:mapping/log/*.xml

orderdb:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.139.13:3306/gj_order
    username: root
    password: 1989513bs
    mappinglocation: classpath*:mapping/order/*.xml

platsettingdb:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.139.13:3306/gj_platsetting
    username: root
    password: 1989513bs
    mappinglocation: classpath*:mapping/platsetting/*.xml

suppliersettingdb:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.139.13:3306/gj_suppliersetting
    username: root
    password: 1989513bs
    mappinglocation: classpath*:mapping/suppliersetting/*.xml
rulesettingdb:
    datasource:
      driver-class-name:  com.mysql.jdbc.Driver
      url: jdbc:mysql://123.56.139.13:3306/gj_rulesetting
      username: root
      password: 1989513bs
      mappinglocation: classpath*:mapping/rulesetting/*.xml

spring:
    datasource:
        name: test
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    cache:
      #缓存名称
      cache-names: platSetCache,salesAirLineSetCache,exactSetCache,currencySetCache
      #缓存最大数量5000条, 缓存失效时间 1分钟
      guava:
        spec: maximumSize=5000,expireAfterWrite=5m

