server:
    port: 8090
    address: 0.0.0.0
    sessionTimeout: 30
    contextPath: /

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mybatis:
    mapperLocations: classpath:mapping/*.xml

spring:
    profiles:
        active: dev

    datasource:
        name: test
        url: jdbc:mysql://10.100.159.49:3500/TCFlyOfficialSales
        username: TCFlyOfficialSales
        password: VWEoeVTwwt2jhQrO91hp
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

