package com.tzq.dal.mapper;

import com.tzq.dal.model.TestOrder;
import com.tzq.dal.model.TestOrderKey;

public interface TestOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TestOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated
     */
    int insert(TestOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated
     */
    int insertSelective(TestOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated
     */
    TestOrder selectByPrimaryKey(TestOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestOrder record);
}